local class_members = {}

class_members["invalidatecache"] = {}

class_members["invalidatecache"]["Constructors"] = {}

class_members["invalidatecache"]["Methods"] = {}

class_members["invalidatecache"]["Arguments"] = {
    "Instance"
}

class_members["invalidatecache"]["Returns"] = {
    "void"
}

class_members["invalidatecache"]["Properties"] = {}

class_members["invalidatecache"]["Events"] = {}

class_members["invalidatecache"]["Callbacks"] = {}

class_members["invalidatecache"]["Types"] = {
    ["Function"] = "void invalidatecache(Instance instance)"
}

class_members["invalidatecache"]["Description"] = "Invalidates an Instance from the executor cache."

class_members["invalidatecache"]["Notes"] = {
    "Legacy alias for cache.invalidate."
}

return class_members
