local class_members = {}

class_members["iscached"] = {}

class_members["iscached"]["Constructors"] = {}

class_members["iscached"]["Methods"] = {}

class_members["iscached"]["Arguments"] = {
    "Instance"
}

class_members["iscached"]["Returns"] = {
    "boolean"
}

class_members["iscached"]["Properties"] = {}

class_members["iscached"]["Events"] = {}

class_members["iscached"]["Callbacks"] = {}

class_members["iscached"]["Types"] = {
    ["Function"] = "boolean iscached(Instance instance)"
}

class_members["iscached"]["Description"] = "Checks if an Instance is cached."

class_members["iscached"]["Notes"] = {
    "Alias for cache.iscached in some executors."
}

return class_members
