local class_members = {}

class_members["keyrelease"] = {}

class_members["keyrelease"]["Constructors"] = {}
class_members["keyrelease"]["Methods"] = {}

class_members["keyrelease"]["Arguments"] = {
    "number"
}

class_members["keyrelease"]["Returns"] = {
    "void"
}

class_members["keyrelease"]["Properties"] = {}
class_members["keyrelease"]["Events"] = {}
class_members["keyrelease"]["Callbacks"] = {}

class_members["keyrelease"]["Types"] = {
    ["Function"] = "void keyrelease(number keycode)"
}

class_members["keyrelease"]["Description"] = "Releases a keyboard key."

return class_members
