local class_members = {}

class_members["makefolder"] = {}

class_members["makefolder"]["Constructors"] = {}

class_members["makefolder"]["Methods"] = {}

class_members["makefolder"]["Arguments"] = {
    "string"
}

class_members["makefolder"]["Returns"] = {
    "void"
}

class_members["makefolder"]["Properties"] = {}

class_members["makefolder"]["Events"] = {}

class_members["makefolder"]["Callbacks"] = {}

class_members["makefolder"]["Examples"] = {
    {
        ["Code"] = [[
makefolder("Scripts")
        ]],
        ["Returns"] = {
            "nil"
        }
    }
}

class_members["makefolder"]["Types"] = {
    ["Function"] = "void makefolder(string path)"
}

class_members["makefolder"]["Description"] = "Creates a new folder."

return class_members
