local class_members = {}

class_members["mousemoveabs"] = {}

class_members["mousemoveabs"]["Constructors"] = {}
class_members["mousemoveabs"]["Methods"] = {}

class_members["mousemoveabs"]["Arguments"] = {
    "number",
    "number"
}

class_members["mousemoveabs"]["Returns"] = {
    "void"
}

class_members["mousemoveabs"]["Properties"] = {}
class_members["mousemoveabs"]["Events"] = {}
class_members["mousemoveabs"]["Callbacks"] = {}

class_members["mousemoveabs"]["Examples"] = {
    {
        ["Code"] = [[
mousemoveabs(500, 300)
        ]],
        ["Returns"] = {
            "void"
        }
    }
}

class_members["mousemoveabs"]["Types"] = {
    ["Function"] = "void mousemoveabs(number x, number y)"
}

class_members["mousemoveabs"]["Description"] = "Moves the mouse cursor to an absolute screen position."

return class_members
