local class_members = {}

class_members["mouse2press"] = {}

class_members["mouse2press"]["Constructors"] = {}
class_members["mouse2press"]["Methods"] = {}

class_members["mouse2press"]["Arguments"] = {}

class_members["mouse2press"]["Returns"] = {
    "void"
}

class_members["mouse2press"]["Properties"] = {}
class_members["mouse2press"]["Events"] = {}
class_members["mouse2press"]["Callbacks"] = {}

class_members["mouse2press"]["Types"] = {
    ["Function"] = "void mouse2press()"
}

class_members["mouse2press"]["Description"] = "Presses and holds the right mouse button."

return class_members
