local class_members = {}

class_members["mouse1release"] = {}

class_members["mouse1release"]["Constructors"] = {}
class_members["mouse1release"]["Methods"] = {}

class_members["mouse1release"]["Arguments"] = {}

class_members["mouse1release"]["Returns"] = {
    "void"
}

class_members["mouse1release"]["Properties"] = {}
class_members["mouse1release"]["Events"] = {}
class_members["mouse1release"]["Callbacks"] = {}

class_members["mouse1release"]["Examples"] = {
    {
        ["Code"] = [[
mouse1release()
        ]],
        ["Returns"] = {
            "void"
        }
    }
}

class_members["mouse1release"]["Types"] = {
    ["Function"] = "void mouse1release()"
}

class_members["mouse1release"]["Description"] = "Releases the left mouse button."

return class_members
