local class_members = {}

class_members["mousescroll"] = {}

class_members["mousescroll"]["Constructors"] = {}
class_members["mousescroll"]["Methods"] = {}

class_members["mousescroll"]["Arguments"] = {
    "number"
}

class_members["mousescroll"]["Returns"] = {
    "void"
}

class_members["mousescroll"]["Properties"] = {}
class_members["mousescroll"]["Events"] = {}
class_members["mousescroll"]["Callbacks"] = {}

class_members["mousescroll"]["Examples"] = {
    {
        ["Code"] = [[
mousescroll(5)
        ]],
        ["Returns"] = {
            "void"
        }
    }
}

class_members["mousescroll"]["Types"] = {
    ["Function"] = "void mousescroll(number amount)"
}

class_members["mousescroll"]["Description"] = "Scrolls the mouse wheel by the specified amount."

return class_members
