local class_members = {}

class_members["mouse2click"] = {}

class_members["mouse2click"]["Constructors"] = {}
class_members["mouse2click"]["Methods"] = {}

class_members["mouse2click"]["Arguments"] = {}

class_members["mouse2click"]["Returns"] = {
    "void"
}

class_members["mouse2click"]["Properties"] = {}
class_members["mouse2click"]["Events"] = {}
class_members["mouse2click"]["Callbacks"] = {}

class_members["mouse2click"]["Examples"] = {
    {
        ["Code"] = [[
mouse2click()
        ]],
        ["Returns"] = {
            "void"
        }
    }
}

class_members["mouse2click"]["Types"] = {
    ["Function"] = "void mouse2click()"
}

class_members["mouse2click"]["Description"] = "Simulates a right mouse button click."

return class_members
