local class_members = {}

class_members["mouse1press"] = {}

class_members["mouse1press"]["Constructors"] = {}
class_members["mouse1press"]["Methods"] = {}

class_members["mouse1press"]["Arguments"] = {}

class_members["mouse1press"]["Returns"] = {
    "void"
}

class_members["mouse1press"]["Properties"] = {}
class_members["mouse1press"]["Events"] = {}
class_members["mouse1press"]["Callbacks"] = {}

class_members["mouse1press"]["Examples"] = {
    {
        ["Code"] = [[
mouse1press()
        ]],
        ["Returns"] = {
            "void"
        }
    }
}

class_members["mouse1press"]["Types"] = {
    ["Function"] = "void mouse1press()"
}

class_members["mouse1press"]["Description"] = "Presses and holds the left mouse button."

return class_members
