local class_members = {}

class_members["mouse2release"] = {}

class_members["mouse2release"]["Constructors"] = {}
class_members["mouse2release"]["Methods"] = {}

class_members["mouse2release"]["Arguments"] = {}

class_members["mouse2release"]["Returns"] = {
    "void"
}

class_members["mouse2release"]["Properties"] = {}
class_members["mouse2release"]["Events"] = {}
class_members["mouse2release"]["Callbacks"] = {}

class_members["mouse2release"]["Types"] = {
    ["Function"] = "void mouse2release()"
}

class_members["mouse2release"]["Description"] = "Releases the right mouse button."

return class_members
