local class_members = {}

class_members["rconsolename"] = {}

class_members["rconsolename"]["Constructors"] = {}
class_members["rconsolename"]["Methods"] = {}

class_members["rconsolename"]["Arguments"] = {
    "string"
}

class_members["rconsolename"]["Returns"] = {
    "void"
}

class_members["rconsolename"]["Properties"] = {}
class_members["rconsolename"]["Events"] = {}
class_members["rconsolename"]["Callbacks"] = {}

class_members["rconsolename"]["Types"] = {
    ["Function"] = "void rconsolename(string title)"
}

class_members["rconsolename"]["Description"] = "Changes the executor console window title."

return class_members
