local class_members = {}

class_members["rconsoleerr"] = {}

class_members["rconsoleerr"]["Constructors"] = {}
class_members["rconsoleerr"]["Methods"] = {}

class_members["rconsoleerr"]["Arguments"] = {
    "string"
}

class_members["rconsoleerr"]["Returns"] = {
    "void"
}

class_members["rconsoleerr"]["Properties"] = {}
class_members["rconsoleerr"]["Events"] = {}
class_members["rconsoleerr"]["Callbacks"] = {}

class_members["rconsoleerr"]["Examples"] = {
    {
        ["Code"] = [[
rconsoleerr("Error message")
        ]],
        ["Returns"] = {
            "void"
        }
    }
}

class_members["rconsoleerr"]["Types"] = {
    ["Function"] = "void rconsoleerr(string text)"
}

class_members["rconsoleerr"]["Description"] = "Prints an error message to the executor console."

return class_members
