local class_members = {}

class_members["rconsoleclear"] = {}

class_members["rconsoleclear"]["Constructors"] = {}
class_members["rconsoleclear"]["Methods"] = {}

class_members["rconsoleclear"]["Arguments"] = {}

class_members["rconsoleclear"]["Returns"] = {
    "void"
}

class_members["rconsoleclear"]["Properties"] = {}
class_members["rconsoleclear"]["Events"] = {}
class_members["rconsoleclear"]["Callbacks"] = {}

class_members["rconsoleclear"]["Types"] = {
    ["Function"] = "void rconsoleclear()"
}

class_members["rconsoleclear"]["Description"] = "Clears all text from the executor console."

return class_members
