local class_members = {}

class_members["replacecache"] = {}

class_members["replacecache"]["Constructors"] = {}

class_members["replacecache"]["Methods"] = {}

class_members["replacecache"]["Arguments"] = {
    "Instance",
    "Instance"
}

class_members["replacecache"]["Returns"] = {
    "void"
}

class_members["replacecache"]["Properties"] = {}

class_members["replacecache"]["Events"] = {}

class_members["replacecache"]["Callbacks"] = {}

class_members["replacecache"]["Types"] = {
    ["Function"] = "void replacecache(Instance old, Instance new)"
}

class_members["replacecache"]["Description"] = "Replaces a cached Instance reference."

class_members["replacecache"]["Notes"] = {
    "Legacy alias for cache.replace."
}

return class_members
