local class_members = {}

class_members["websocket.onmessage"] = {}

class_members["websocket.onmessage"]["Constructors"] = {}
class_members["websocket.onmessage"]["Methods"] = {}

class_members["websocket.onmessage"]["Arguments"] = {
    "function"
}

class_members["websocket.onmessage"]["Returns"] = {
    "void"
}

class_members["websocket.onmessage"]["Properties"] = {}
class_members["websocket.onmessage"]["Events"] = {}
class_members["websocket.onmessage"]["Callbacks"] = {}

class_members["websocket.onmessage"]["Types"] = {
    ["Property"] = "function WebSocket.OnMessage"
}

class_members["websocket.onmessage"]["Description"] = "Callback fired when a WebSocket message is received."

return class_members
