local class_members = {}

class_members["websocket.close"] = {}

class_members["websocket.close"]["Constructors"] = {}
class_members["websocket.close"]["Methods"] = {}

class_members["websocket.close"]["Arguments"] = {}

class_members["websocket.close"]["Returns"] = {
    "void"
}

class_members["websocket.close"]["Properties"] = {}
class_members["websocket.close"]["Events"] = {}
class_members["websocket.close"]["Callbacks"] = {}

class_members["websocket.close"]["Examples"] = {
    {
        ["Code"] = [[
ws:Close()
        ]],
        ["Returns"] = {
            "void"
        }
    }
}

class_members["websocket.close"]["Types"] = {
    ["Method"] = "void WebSocket:Close()"
}

class_members["websocket.close"]["Description"] = "Closes an active WebSocket connection."

return class_members
