local class_members = {}

class_members["UserInputService"] = {}

class_members["UserInputService"]["AccelerometerEnabled"] = {
    Type = "Property",
    ReadOnly = true,
    ValueType = { Category = "Primitive", Name = "bool" },
    From = "UserInputService"
}

class_members["UserInputService"]["Archivable"] = {
    Type = "Property",
    ReadOnly = false,
    ValueType = { Category = "Primitive", Name = "bool" },
    From = "Instance"
}

class_members["UserInputService"]["Attributes"] = {
    Type = "Property",
    ReadOnly = true,
    ValueType = { Category = "Primitive", Name = "string" },
    From = "Instance"
}

class_members["UserInputService"]["AttributesReplicate"] = {
    Type = "Property",
    ReadOnly = false,
    ValueType = { Category = "Primitive", Name = "string" },
    From = "Instance"
}

class_members["UserInputService"]["AttributesSerialize"] = {
    Type = "Property",
    ReadOnly = false,
    ValueType = { Category = "DataType", Name = "BinaryString" },
    From = "Instance"
}

class_members["UserInputService"]["BottomBarSize"] = {
    Type = "Property",
    ReadOnly = true,
    ValueType = { Category = "DataType", Name = "Vector2" },
    From = "UserInputService"
}

class_members["UserInputService"]["Capabilities"] = {
    Type = "Property",
    ReadOnly = false,
    ValueType = { Category = "DataType", Name = "SecurityCapabilities" },
    From = "Instance"
}

class_members["UserInputService"]["ClassName"] = {
    Type = "Property",
    ReadOnly = true,
    ValueType = { Category = "Primitive", Name = "string" },
    From = "Object"
}

class_members["UserInputService"]["DataCost"] = {
    Type = "Property",
    ReadOnly = true,
    ValueType = { Category = "Primitive", Name = "int" },
    From = "Instance"
}

class_members["UserInputService"]["DefinesCapabilities"] = {
    Type = "Property",
    ReadOnly = false,
    ValueType = { Category = "Primitive", Name = "bool" },
    From = "Instance"
}

class_members["UserInputService"]["GamepadEnabled"] = {
    Type = "Property",
    ReadOnly = true,
    ValueType = { Category = "Primitive", Name = "bool" },
    From = "UserInputService"
}

class_members["UserInputService"]["GyroscopeEnabled"] = {
    Type = "Property",
    ReadOnly = true,
    ValueType = { Category = "Primitive", Name = "bool" },
    From = "UserInputService"
}

class_members["UserInputService"]["HistoryId"] = {
    Type = "Property",
    ReadOnly = false,
    ValueType = { Category = "DataType", Name = "UniqueId" },
    From = "Instance"
}

class_members["UserInputService"]["IsInSandbox"] = {
    Type = "Property",
    ReadOnly = true,
    ValueType = { Category = "Primitive", Name = "bool" },
    From = "Instance"
}

class_members["UserInputService"]["KeyboardEnabled"] = {
    Type = "Property",
    ReadOnly = true,
    ValueType = { Category = "Primitive", Name = "bool" },
    From = "UserInputService"
}

class_members["UserInputService"]["LegacyInputEventsEnabled"] = {
    Type = "Property",
    ReadOnly = false,
    ValueType = { Category = "Primitive", Name = "bool" },
    From = "UserInputService"
}

class_members["UserInputService"]["ModalEnabled"] = {
    Type = "Property",
    ReadOnly = false,
    ValueType = { Category = "Primitive", Name = "bool" },
    From = "UserInputService"
}

class_members["UserInputService"]["MouseBehavior"] = {
    Type = "Property",
    ReadOnly = false,
    ValueType = { Category = "Enum", Name = "MouseBehavior" },
    From = "UserInputService"
}

class_members["UserInputService"]["MouseDeltaSensitivity"] = {
    Type = "Property",
    ReadOnly = false,
    ValueType = { Category = "Primitive", Name = "float" },
    From = "UserInputService"
}

class_members["UserInputService"]["MouseEnabled"] = {
    Type = "Property",
    ReadOnly = true,
    ValueType = { Category = "Primitive", Name = "bool" },
    From = "UserInputService"
}

class_members["UserInputService"]["MouseIcon"] = {
    Type = "Property",
    ReadOnly = false,
    ValueType = { Category = "DataType", Name = "ContentId" },
    From = "UserInputService"
}

class_members["UserInputService"]["MouseIconContent"] = {
    Type = "Property",
    ReadOnly = false,
    ValueType = { Category = "DataType", Name = "Content" },
    From = "UserInputService"
}

class_members["UserInputService"]["MouseIconEnabled"] = {
    Type = "Property",
    ReadOnly = false,
    ValueType = { Category = "Primitive", Name = "bool" },
    From = "UserInputService"
}

class_members["UserInputService"]["Name"] = {
    Type = "Property",
    ReadOnly = false,
    ValueType = { Category = "Primitive", Name = "string" },
    From = "Instance"
}

class_members["UserInputService"]["NavBarSize"] = {
    Type = "Property",
    ReadOnly = true,
    ValueType = { Category = "DataType", Name = "Vector2" },
    From = "UserInputService"
}

class_members["UserInputService"]["OnScreenKeyboardAnimationDuration"] = {
    Type = "Property",
    ReadOnly = true,
    ValueType = { Category = "Primitive", Name = "double" },
    From = "UserInputService"
}

class_members["UserInputService"]["OnScreenKeyboardPosition"] = {
    Type = "Property",
    ReadOnly = true,
    ValueType = { Category = "DataType", Name = "Vector2" },
    From = "UserInputService"
}

class_members["UserInputService"]["OnScreenKeyboardSize"] = {
    Type = "Property",
    ReadOnly = true,
    ValueType = { Category = "DataType", Name = "Vector2" },
    From = "UserInputService"
}

class_members["UserInputService"]["OnScreenKeyboardVisible"] = {
    Type = "Property",
    ReadOnly = true,
    ValueType = { Category = "Primitive", Name = "bool" },
    From = "UserInputService"
}

class_members["UserInputService"]["OverrideMouseIconBehavior"] = {
    Type = "Property",
    ReadOnly = false,
    ValueType = { Category = "Enum", Name = "OverrideMouseIconBehavior" },
    From = "UserInputService"
}

class_members["UserInputService"]["Parent"] = {
    Type = "Property",
    ReadOnly = false,
    ValueType = { Category = "Class", Name = "Instance" },
    From = "Instance"
}

class_members["UserInputService"]["PredictionMode"] = {
    Type = "Property",
    ReadOnly = true,
    ValueType = { Category = "Enum", Name = "PredictionMode" },
    From = "Instance"
}

class_members["UserInputService"]["PreferredInput"] = {
    Type = "Property",
    ReadOnly = true,
    ValueType = { Category = "Enum", Name = "PreferredInput" },
    From = "UserInputService"
}

class_members["UserInputService"]["PropertyStatusStudio"] = {
    Type = "Property",
    ReadOnly = true,
    ValueType = { Category = "Enum", Name = "PropertyStatus" },
    From = "Instance"
}

class_members["UserInputService"]["RightBarSize"] = {
    Type = "Property",
    ReadOnly = true,
    ValueType = { Category = "DataType", Name = "Vector2" },
    From = "UserInputService"
}

class_members["UserInputService"]["RobloxLocked"] = {
    Type = "Property",
    ReadOnly = false,
    ValueType = { Category = "Primitive", Name = "bool" },
    From = "Instance"
}

class_members["UserInputService"]["Sandboxed"] = {
    Type = "Property",
    ReadOnly = false,
    ValueType = { Category = "Primitive", Name = "bool" },
    From = "Instance"
}

class_members["UserInputService"]["SourceAssetId"] = {
    Type = "Property",
    ReadOnly = false,
    ValueType = { Category = "Primitive", Name = "int64" },
    From = "Instance"
}

class_members["UserInputService"]["StatusBarSize"] = {
    Type = "Property",
    ReadOnly = true,
    ValueType = { Category = "DataType", Name = "Vector2" },
    From = "UserInputService"
}

class_members["UserInputService"]["Tags"] = {
    Type = "Property",
    ReadOnly = false,
    ValueType = { Category = "DataType", Name = "SharedString" },
    From = "Instance"
}

class_members["UserInputService"]["TouchEnabled"] = {
    Type = "Property",
    ReadOnly = true,
    ValueType = { Category = "Primitive", Name = "bool" },
    From = "UserInputService"
}

class_members["UserInputService"]["TouchScreenEnabled"] = {
    Type = "Property",
    ReadOnly = true,
    ValueType = { Category = "Primitive", Name = "bool" },
    From = "UserInputService"
}

class_members["UserInputService"]["UniqueId"] = {
    Type = "Property",
    ReadOnly = false,
    ValueType = { Category = "DataType", Name = "UniqueId" },
    From = "Instance"
}

class_members["UserInputService"]["UserHeadCFrame"] = {
    Type = "Property",
    ReadOnly = true,
    ValueType = { Category = "DataType", Name = "CFrame" },
    From = "UserInputService"
}

class_members["UserInputService"]["VREnabled"] = {
    Type = "Property",
    ReadOnly = true,
    ValueType = { Category = "Primitive", Name = "bool" },
    From = "UserInputService"
}

class_members["UserInputService"]["archivable"] = {
    Type = "Property",
    ReadOnly = false,
    ValueType = { Category = "Primitive", Name = "bool" },
    From = "Instance"
}

class_members["UserInputService"]["className"] = {
    Type = "Property",
    ReadOnly = true,
    ValueType = { Category = "Primitive", Name = "string" },
    From = "Object"
}

class_members["UserInputService"]["numExpectedDirectChildren"] = {
    Type = "Property",
    ReadOnly = false,
    ValueType = { Category = "Primitive", Name = "int" },
    From = "Instance"
}

class_members["UserInputService"]["AddTag"] = {
    Type = "Function",
    ReturnType = { Category = "Primitive", Name = "null" },
    Parameters = { { Name = "tag", Type = { Category = "Primitive", Name = "string" } } },
    From = "Instance"
}

class_members["UserInputService"]["ClearAllChildren"] = {
    Type = "Function",
    ReturnType = { Category = "Primitive", Name = "null" },
    Parameters = {},
    From = "Instance"
}

class_members["UserInputService"]["Clone"] = {
    Type = "Function",
    ReturnType = { Category = "Class", Name = "Instance" },
    Parameters = {},
    From = "Instance"
}

class_members["UserInputService"]["CreateVirtualInput"] = {
    Type = "Function",
    ReturnType = { Category = "Class", Name = "Object" },
    Parameters = {},
    From = "UserInputService"
}

class_members["UserInputService"]["Destroy"] = {
    Type = "Function",
    ReturnType = { Category = "Primitive", Name = "null" },
    Parameters = {},
    From = "Instance"
}

class_members["UserInputService"]["FindFirstAncestor"] = {
    Type = "Function",
    ReturnType = { Category = "Class", Name = "Instance" },
    Parameters = { { Name = "name", Type = { Category = "Primitive", Name = "string" } } },
    From = "Instance"
}

class_members["UserInputService"]["FindFirstAncestorOfClass"] = {
    Type = "Function",
    ReturnType = { Category = "Class", Name = "Instance" },
    Parameters = { { Name = "className", Type = { Category = "Primitive", Name = "string" } } },
    From = "Instance"
}

class_members["UserInputService"]["FindFirstAncestorWhichIsA"] = {
    Type = "Function",
    ReturnType = { Category = "Class", Name = "Instance" },
    Parameters = { { Name = "className", Type = { Category = "Primitive", Name = "string" } } },
    From = "Instance"
}

class_members["UserInputService"]["FindFirstChild"] = {
    Type = "Function",
    ReturnType = { Category = "Class", Name = "Instance" },
    Parameters = { { Name = "name", Type = { Category = "Primitive", Name = "string" } }, { Name = "recursive", Type = { Category = "Primitive", Name = "bool" } } },
    From = "Instance"
}

class_members["UserInputService"]["FindFirstChildOfClass"] = {
    Type = "Function",
    ReturnType = { Category = "Class", Name = "Instance" },
    Parameters = { { Name = "className", Type = { Category = "Primitive", Name = "string" } } },
    From = "Instance"
}

class_members["UserInputService"]["FindFirstChildWhichIsA"] = {
    Type = "Function",
    ReturnType = { Category = "Class", Name = "Instance" },
    Parameters = { { Name = "className", Type = { Category = "Primitive", Name = "string" } }, { Name = "recursive", Type = { Category = "Primitive", Name = "bool" } } },
    From = "Instance"
}

class_members["UserInputService"]["FindFirstDescendant"] = {
    Type = "Function",
    ReturnType = { Category = "Class", Name = "Instance" },
    Parameters = { { Name = "name", Type = { Category = "Primitive", Name = "string" } } },
    From = "Instance"
}

class_members["UserInputService"]["GamepadSupports"] = {
    Type = "Function",
    ReturnType = { Category = "Primitive", Name = "bool" },
    Parameters = { { Name = "gamepadNum", Type = { Category = "Enum", Name = "UserInputType" } }, { Name = "gamepadKeyCode", Type = { Category = "Enum", Name = "KeyCode" } } },
    From = "UserInputService"
}

class_members["UserInputService"]["GetActor"] = {
    Type = "Function",
    ReturnType = { Category = "Class", Name = "Actor" },
    Parameters = {},
    From = "Instance"
}

class_members["UserInputService"]["GetAttribute"] = {
    Type = "Function",
    ReturnType = { Category = "Group", Name = "Variant" },
    Parameters = { { Name = "attribute", Type = { Category = "Primitive", Name = "string" } } },
    From = "Instance"
}

class_members["UserInputService"]["GetAttributeChangedSignal"] = {
    Type = "Function",
    ReturnType = { Category = "DataType", Name = "RBXScriptSignal" },
    Parameters = { { Name = "attribute", Type = { Category = "Primitive", Name = "string" } } },
    From = "Instance"
}

class_members["UserInputService"]["GetAttributes"] = {
    Type = "Function",
    ReturnType = { Category = "Group", Name = "Dictionary" },
    Parameters = {},
    From = "Instance"
}

class_members["UserInputService"]["GetChildren"] = {
    Type = "Function",
    ReturnType = { Category = "DataType", Name = "Instances" },
    Parameters = {},
    From = "Instance"
}

class_members["UserInputService"]["GetConnectedGamepads"] = {
    Type = "Function",
    ReturnType = { Category = "Group", Name = "Array" },
    Parameters = {},
    From = "UserInputService"
}

class_members["UserInputService"]["GetDebugId"] = {
    Type = "Function",
    ReturnType = { Category = "Primitive", Name = "string" },
    Parameters = { { Name = "scopeLength", Type = { Category = "Primitive", Name = "int" } } },
    From = "Instance"
}

class_members["UserInputService"]["GetDescendants"] = {
    Type = "Function",
    ReturnType = { Category = "DataType", Name = "Instances" },
    Parameters = {},
    From = "Instance"
}

class_members["UserInputService"]["GetDeviceAcceleration"] = {
    Type = "Function",
    ReturnType = { Category = "Class", Name = "InputObject" },
    Parameters = {},
    From = "UserInputService"
}

class_members["UserInputService"]["GetDeviceGravity"] = {
    Type = "Function",
    ReturnType = { Category = "Class", Name = "InputObject" },
    Parameters = {},
    From = "UserInputService"
}

class_members["UserInputService"]["GetDeviceLevel"] = {
    Type = "Function",
    ReturnType = { Category = "Enum", Name = "DeviceLevel" },
    Parameters = {},
    From = "UserInputService"
}

class_members["UserInputService"]["GetDeviceRotation"] = {
    Type = "Function",
    ReturnType = { Category = "Group", Name = "Tuple" },
    Parameters = {},
    From = "UserInputService"
}

class_members["UserInputService"]["GetDeviceType"] = {
    Type = "Function",
    ReturnType = { Category = "Enum", Name = "DeviceType" },
    Parameters = {},
    From = "UserInputService"
}

class_members["UserInputService"]["GetFocusedTextBox"] = {
    Type = "Function",
    ReturnType = { Category = "Class", Name = "TextBox" },
    Parameters = {},
    From = "UserInputService"
}

class_members["UserInputService"]["GetFullName"] = {
    Type = "Function",
    ReturnType = { Category = "Primitive", Name = "string" },
    Parameters = {},
    From = "Instance"
}

class_members["UserInputService"]["GetGamepadConnected"] = {
    Type = "Function",
    ReturnType = { Category = "Primitive", Name = "bool" },
    Parameters = { { Name = "gamepadNum", Type = { Category = "Enum", Name = "UserInputType" } } },
    From = "UserInputService"
}

class_members["UserInputService"]["GetGamepadState"] = {
    Type = "Function",
    ReturnType = { Category = "DataType", Name = "Instances" },
    Parameters = { { Name = "gamepadNum", Type = { Category = "Enum", Name = "UserInputType" } } },
    From = "UserInputService"
}

class_members["UserInputService"]["GetImageForKeyCode"] = {
    Type = "Function",
    ReturnType = { Category = "DataType", Name = "ContentId" },
    Parameters = { { Name = "keyCode", Type = { Category = "Enum", Name = "KeyCode" } } },
    From = "UserInputService"
}

class_members["UserInputService"]["GetKeysPressed"] = {
    Type = "Function",
    ReturnType = { Category = "DataType", Name = "Instances" },
    Parameters = {},
    From = "UserInputService"
}

class_members["UserInputService"]["GetLastInputType"] = {
    Type = "Function",
    ReturnType = { Category = "Enum", Name = "UserInputType" },
    Parameters = {},
    From = "UserInputService"
}

class_members["UserInputService"]["GetMouseButtonsPressed"] = {
    Type = "Function",
    ReturnType = { Category = "DataType", Name = "Instances" },
    Parameters = {},
    From = "UserInputService"
}

class_members["UserInputService"]["GetMouseDelta"] = {
    Type = "Function",
    ReturnType = { Category = "DataType", Name = "Vector2" },
    Parameters = {},
    From = "UserInputService"
}

class_members["UserInputService"]["GetMouseLocation"] = {
    Type = "Function",
    ReturnType = { Category = "DataType", Name = "Vector2" },
    Parameters = {},
    From = "UserInputService"
}

class_members["UserInputService"]["GetNavigationGamepads"] = {
    Type = "Function",
    ReturnType = { Category = "Group", Name = "Array" },
    Parameters = {},
    From = "UserInputService"
}

class_members["UserInputService"]["GetPasteText"] = {
    Type = "Function",
    ReturnType = { Category = "Primitive", Name = "string" },
    Parameters = {},
    From = "UserInputService"
}

class_members["UserInputService"]["GetPlatform"] = {
    Type = "Function",
    ReturnType = { Category = "Enum", Name = "Platform" },
    Parameters = {},
    From = "UserInputService"
}

class_members["UserInputService"]["GetPropertyChangedSignal"] = {
    Type = "Function",
    ReturnType = { Category = "DataType", Name = "RBXScriptSignal" },
    Parameters = { { Name = "property", Type = { Category = "Primitive", Name = "string" } } },
    From = "Object"
}

class_members["UserInputService"]["GetStringForKeyCode"] = {
    Type = "Function",
    ReturnType = { Category = "Primitive", Name = "string" },
    Parameters = { { Name = "keyCode", Type = { Category = "Enum", Name = "KeyCode" } }, { Name = "format", Type = { Category = "Enum", Name = "KeyCodeStringFormat" } } },
    From = "UserInputService"
}

class_members["UserInputService"]["GetStyled"] = {
    Type = "Function",
    ReturnType = { Category = "Group", Name = "Variant" },
    Parameters = { { Name = "name", Type = { Category = "Primitive", Name = "string" } }, { Name = "selector", Type = { Category = "Primitive", Name = "string?" } } },
    From = "Instance"
}

class_members["UserInputService"]["GetStyledPropertyChangedSignal"] = {
    Type = "Function",
    ReturnType = { Category = "DataType", Name = "RBXScriptSignal" },
    Parameters = { { Name = "property", Type = { Category = "Primitive", Name = "string" } } },
    From = "Instance"
}

class_members["UserInputService"]["GetSupportedGamepadKeyCodes"] = {
    Type = "Function",
    ReturnType = { Category = "Group", Name = "Array" },
    Parameters = { { Name = "gamepadNum", Type = { Category = "Enum", Name = "UserInputType" } } },
    From = "UserInputService"
}

class_members["UserInputService"]["GetTags"] = {
    Type = "Function",
    ReturnType = { Category = "Group", Name = "Array" },
    Parameters = {},
    From = "Instance"
}

class_members["UserInputService"]["GetUserCFrame"] = {
    Type = "Function",
    ReturnType = { Category = "DataType", Name = "CFrame" },
    Parameters = { { Name = "type", Type = { Category = "Enum", Name = "UserCFrame" } } },
    From = "UserInputService"
}

class_members["UserInputService"]["HasTag"] = {
    Type = "Function",
    ReturnType = { Category = "Primitive", Name = "bool" },
    Parameters = { { Name = "tag", Type = { Category = "Primitive", Name = "string" } } },
    From = "Instance"
}

class_members["UserInputService"]["IsA"] = {
    Type = "Function",
    ReturnType = { Category = "Primitive", Name = "bool" },
    Parameters = { { Name = "className", Type = { Category = "Primitive", Name = "string" } } },
    From = "Object"
}

class_members["UserInputService"]["IsAncestorOf"] = {
    Type = "Function",
    ReturnType = { Category = "Primitive", Name = "bool" },
    Parameters = { { Name = "descendant", Type = { Category = "Class", Name = "Instance" } } },
    From = "Instance"
}

class_members["UserInputService"]["IsDescendantOf"] = {
    Type = "Function",
    ReturnType = { Category = "Primitive", Name = "bool" },
    Parameters = { { Name = "ancestor", Type = { Category = "Class", Name = "Instance" } } },
    From = "Instance"
}

class_members["UserInputService"]["IsGamepadButtonDown"] = {
    Type = "Function",
    ReturnType = { Category = "Primitive", Name = "bool" },
    Parameters = { { Name = "gamepadNum", Type = { Category = "Enum", Name = "UserInputType" } }, { Name = "gamepadKeyCode", Type = { Category = "Enum", Name = "KeyCode" } } },
    From = "UserInputService"
}

class_members["UserInputService"]["IsKeyDown"] = {
    Type = "Function",
    ReturnType = { Category = "Primitive", Name = "bool" },
    Parameters = { { Name = "keyCode", Type = { Category = "Enum", Name = "KeyCode" } } },
    From = "UserInputService"
}

class_members["UserInputService"]["IsMouseButtonPressed"] = {
    Type = "Function",
    ReturnType = { Category = "Primitive", Name = "bool" },
    Parameters = { { Name = "mouseButton", Type = { Category = "Enum", Name = "UserInputType" } } },
    From = "UserInputService"
}

class_members["UserInputService"]["IsNavigationGamepad"] = {
    Type = "Function",
    ReturnType = { Category = "Primitive", Name = "bool" },
    Parameters = { { Name = "gamepadEnum", Type = { Category = "Enum", Name = "UserInputType" } } },
    From = "UserInputService"
}

class_members["UserInputService"]["IsPropertyModified"] = {
    Type = "Function",
    ReturnType = { Category = "Primitive", Name = "bool" },
    Parameters = { { Name = "property", Type = { Category = "Primitive", Name = "string" } } },
    From = "Instance"
}

class_members["UserInputService"]["QueryDescendants"] = {
    Type = "Function",
    ReturnType = { Category = "DataType", Name = "Instances" },
    Parameters = { { Name = "selector", Type = { Category = "Primitive", Name = "string" } } },
    From = "Instance"
}

class_members["UserInputService"]["RecenterUserHeadCFrame"] = {
    Type = "Function",
    ReturnType = { Category = "Primitive", Name = "null" },
    Parameters = {},
    From = "UserInputService"
}

class_members["UserInputService"]["Remove"] = {
    Type = "Function",
    ReturnType = { Category = "Primitive", Name = "null" },
    Parameters = {},
    From = "Instance"
}

class_members["UserInputService"]["RemoveTag"] = {
    Type = "Function",
    ReturnType = { Category = "Primitive", Name = "null" },
    Parameters = { { Name = "tag", Type = { Category = "Primitive", Name = "string" } } },
    From = "Instance"
}

class_members["UserInputService"]["ResetPropertyToDefault"] = {
    Type = "Function",
    ReturnType = { Category = "Primitive", Name = "null" },
    Parameters = { { Name = "property", Type = { Category = "Primitive", Name = "string" } } },
    From = "Instance"
}

class_members["UserInputService"]["SendAppUISizes"] = {
    Type = "Function",
    ReturnType = { Category = "Primitive", Name = "null" },
    Parameters = { { Name = "statusBarSize", Type = { Category = "DataType", Name = "Vector2" } }, { Name = "navBarSize", Type = { Category = "DataType", Name = "Vector2" } }, { Name = "bottomBarSize", Type = { Category = "DataType", Name = "Vector2" } }, { Name = "rightBarSize", Type = { Category = "DataType", Name = "Vector2" } } },
    From = "UserInputService"
}

class_members["UserInputService"]["SetAttribute"] = {
    Type = "Function",
    ReturnType = { Category = "Primitive", Name = "null" },
    Parameters = { { Name = "attribute", Type = { Category = "Primitive", Name = "string" } }, { Name = "value", Type = { Category = "Group", Name = "Variant" } } },
    From = "Instance"
}

class_members["UserInputService"]["SetNavigationGamepad"] = {
    Type = "Function",
    ReturnType = { Category = "Primitive", Name = "null" },
    Parameters = { { Name = "gamepadEnum", Type = { Category = "Enum", Name = "UserInputType" } }, { Name = "enabled", Type = { Category = "Primitive", Name = "bool" } } },
    From = "UserInputService"
}

class_members["UserInputService"]["WaitForChild"] = {
    Type = "Function",
    ReturnType = { Category = "Class", Name = "Instance" },
    Parameters = { { Name = "childName", Type = { Category = "Primitive", Name = "string" } }, { Name = "timeOut", Type = { Category = "Primitive", Name = "double" } } },
    From = "Instance"
}

class_members["UserInputService"]["children"] = {
    Type = "Function",
    ReturnType = { Category = "DataType", Name = "Instances" },
    Parameters = {},
    From = "Instance"
}

class_members["UserInputService"]["clone"] = {
    Type = "Function",
    ReturnType = { Category = "Class", Name = "Instance" },
    Parameters = {},
    From = "Instance"
}

class_members["UserInputService"]["destroy"] = {
    Type = "Function",
    ReturnType = { Category = "Primitive", Name = "null" },
    Parameters = {},
    From = "Instance"
}

class_members["UserInputService"]["findFirstChild"] = {
    Type = "Function",
    ReturnType = { Category = "Class", Name = "Instance" },
    Parameters = { { Name = "name", Type = { Category = "Primitive", Name = "string" } }, { Name = "recursive", Type = { Category = "Primitive", Name = "bool" } } },
    From = "Instance"
}

class_members["UserInputService"]["getChildren"] = {
    Type = "Function",
    ReturnType = { Category = "DataType", Name = "Instances" },
    Parameters = {},
    From = "Instance"
}

class_members["UserInputService"]["isA"] = {
    Type = "Function",
    ReturnType = { Category = "Primitive", Name = "bool" },
    Parameters = { { Name = "className", Type = { Category = "Primitive", Name = "string" } } },
    From = "Object"
}

class_members["UserInputService"]["isDescendantOf"] = {
    Type = "Function",
    ReturnType = { Category = "Primitive", Name = "bool" },
    Parameters = { { Name = "ancestor", Type = { Category = "Class", Name = "Instance" } } },
    From = "Instance"
}

class_members["UserInputService"]["remove"] = {
    Type = "Function",
    ReturnType = { Category = "Primitive", Name = "null" },
    Parameters = {},
    From = "Instance"
}

class_members["UserInputService"]["AncestryChanged"] = {
    Type = "Event",
    Parameters = { { Name = "child", Type = { Category = "Class", Name = "Instance" } }, { Name = "parent", Type = { Category = "Class", Name = "Instance" } } },
    From = "Instance"
}

class_members["UserInputService"]["AttributeChanged"] = {
    Type = "Event",
    Parameters = { { Name = "attribute", Type = { Category = "Primitive", Name = "string" } } },
    From = "Instance"
}

class_members["UserInputService"]["Changed"] = {
    Type = "Event",
    Parameters = { { Name = "property", Type = { Category = "Primitive", Name = "string" } } },
    From = "Object"
}

class_members["UserInputService"]["ChildAdded"] = {
    Type = "Event",
    Parameters = { { Name = "child", Type = { Category = "Class", Name = "Instance" } } },
    From = "Instance"
}

class_members["UserInputService"]["ChildRemoved"] = {
    Type = "Event",
    Parameters = { { Name = "child", Type = { Category = "Class", Name = "Instance" } } },
    From = "Instance"
}

class_members["UserInputService"]["DescendantAdded"] = {
    Type = "Event",
    Parameters = { { Name = "descendant", Type = { Category = "Class", Name = "Instance" } } },
    From = "Instance"
}

class_members["UserInputService"]["DescendantRemoving"] = {
    Type = "Event",
    Parameters = { { Name = "descendant", Type = { Category = "Class", Name = "Instance" } } },
    From = "Instance"
}

class_members["UserInputService"]["Destroying"] = {
    Type = "Event",
    Parameters = {},
    From = "Instance"
}

class_members["UserInputService"]["DeviceAccelerationChanged"] = {
    Type = "Event",
    Parameters = { { Name = "acceleration", Type = { Category = "Class", Name = "InputObject" } } },
    From = "UserInputService"
}

class_members["UserInputService"]["DeviceGravityChanged"] = {
    Type = "Event",
    Parameters = { { Name = "gravity", Type = { Category = "Class", Name = "InputObject" } } },
    From = "UserInputService"
}

class_members["UserInputService"]["DeviceRotationChanged"] = {
    Type = "Event",
    Parameters = { { Name = "rotation", Type = { Category = "Class", Name = "InputObject" } }, { Name = "cframe", Type = { Category = "DataType", Name = "CFrame" } } },
    From = "UserInputService"
}

class_members["UserInputService"]["GamepadConnected"] = {
    Type = "Event",
    Parameters = { { Name = "gamepadNum", Type = { Category = "Enum", Name = "UserInputType" } } },
    From = "UserInputService"
}

class_members["UserInputService"]["GamepadDisconnected"] = {
    Type = "Event",
    Parameters = { { Name = "gamepadNum", Type = { Category = "Enum", Name = "UserInputType" } } },
    From = "UserInputService"
}

class_members["UserInputService"]["InputBegan"] = {
    Type = "Event",
    Parameters = { { Name = "input", Type = { Category = "Class", Name = "InputObject" } }, { Name = "gameProcessedEvent", Type = { Category = "Primitive", Name = "bool" } } },
    From = "UserInputService"
}

class_members["UserInputService"]["InputChanged"] = {
    Type = "Event",
    Parameters = { { Name = "input", Type = { Category = "Class", Name = "InputObject" } }, { Name = "gameProcessedEvent", Type = { Category = "Primitive", Name = "bool" } } },
    From = "UserInputService"
}

class_members["UserInputService"]["InputEnded"] = {
    Type = "Event",
    Parameters = { { Name = "input", Type = { Category = "Class", Name = "InputObject" } }, { Name = "gameProcessedEvent", Type = { Category = "Primitive", Name = "bool" } } },
    From = "UserInputService"
}

class_members["UserInputService"]["JumpRequest"] = {
    Type = "Event",
    Parameters = {},
    From = "UserInputService"
}

class_members["UserInputService"]["LastInputTypeChanged"] = {
    Type = "Event",
    Parameters = { { Name = "lastInputType", Type = { Category = "Enum", Name = "UserInputType" } } },
    From = "UserInputService"
}

class_members["UserInputService"]["PointerAction"] = {
    Type = "Event",
    Parameters = { { Name = "wheel", Type = { Category = "Primitive", Name = "float" } }, { Name = "pan", Type = { Category = "DataType", Name = "Vector2" } }, { Name = "pinch", Type = { Category = "Primitive", Name = "float" } }, { Name = "gameProcessedEvent", Type = { Category = "Primitive", Name = "bool" } } },
    From = "UserInputService"
}

class_members["UserInputService"]["StatusBarTapped"] = {
    Type = "Event",
    Parameters = { { Name = "position", Type = { Category = "DataType", Name = "Vector2" } } },
    From = "UserInputService"
}

class_members["UserInputService"]["StyledPropertiesChanged"] = {
    Type = "Event",
    Parameters = {},
    From = "Instance"
}

class_members["UserInputService"]["TextBoxFocusReleased"] = {
    Type = "Event",
    Parameters = { { Name = "textboxReleased", Type = { Category = "Class", Name = "TextBox" } } },
    From = "UserInputService"
}

class_members["UserInputService"]["TextBoxFocused"] = {
    Type = "Event",
    Parameters = { { Name = "textboxFocused", Type = { Category = "Class", Name = "TextBox" } } },
    From = "UserInputService"
}

class_members["UserInputService"]["TouchDrag"] = {
    Type = "Event",
    Parameters = { { Name = "dragDirection", Type = { Category = "Enum", Name = "SwipeDirection" } }, { Name = "numberOfTouches", Type = { Category = "Primitive", Name = "int" } }, { Name = "gameProcessedEvent", Type = { Category = "Primitive", Name = "bool" } } },
    From = "UserInputService"
}

class_members["UserInputService"]["TouchEnded"] = {
    Type = "Event",
    Parameters = { { Name = "touch", Type = { Category = "Class", Name = "InputObject" } }, { Name = "gameProcessedEvent", Type = { Category = "Primitive", Name = "bool" } } },
    From = "UserInputService"
}

class_members["UserInputService"]["TouchLongPress"] = {
    Type = "Event",
    Parameters = { { Name = "touchPositions", Type = { Category = "Group", Name = "Array" } }, { Name = "state", Type = { Category = "Enum", Name = "UserInputState" } }, { Name = "gameProcessedEvent", Type = { Category = "Primitive", Name = "bool" } } },
    From = "UserInputService"
}

class_members["UserInputService"]["TouchMoved"] = {
    Type = "Event",
    Parameters = { { Name = "touch", Type = { Category = "Class", Name = "InputObject" } }, { Name = "gameProcessedEvent", Type = { Category = "Primitive", Name = "bool" } } },
    From = "UserInputService"
}

class_members["UserInputService"]["TouchPan"] = {
    Type = "Event",
    Parameters = { { Name = "touchPositions", Type = { Category = "Group", Name = "Array" } }, { Name = "totalTranslation", Type = { Category = "DataType", Name = "Vector2" } }, { Name = "velocity", Type = { Category = "DataType", Name = "Vector2" } }, { Name = "state", Type = { Category = "Enum", Name = "UserInputState" } }, { Name = "gameProcessedEvent", Type = { Category = "Primitive", Name = "bool" } } },
    From = "UserInputService"
}

class_members["UserInputService"]["TouchPinch"] = {
    Type = "Event",
    Parameters = { { Name = "touchPositions", Type = { Category = "Group", Name = "Array" } }, { Name = "scale", Type = { Category = "Primitive", Name = "float" } }, { Name = "velocity", Type = { Category = "Primitive", Name = "float" } }, { Name = "state", Type = { Category = "Enum", Name = "UserInputState" } }, { Name = "gameProcessedEvent", Type = { Category = "Primitive", Name = "bool" } } },
    From = "UserInputService"
}

class_members["UserInputService"]["TouchRotate"] = {
    Type = "Event",
    Parameters = { { Name = "touchPositions", Type = { Category = "Group", Name = "Array" } }, { Name = "rotation", Type = { Category = "Primitive", Name = "float" } }, { Name = "velocity", Type = { Category = "Primitive", Name = "float" } }, { Name = "state", Type = { Category = "Enum", Name = "UserInputState" } }, { Name = "gameProcessedEvent", Type = { Category = "Primitive", Name = "bool" } } },
    From = "UserInputService"
}

class_members["UserInputService"]["TouchStarted"] = {
    Type = "Event",
    Parameters = { { Name = "touch", Type = { Category = "Class", Name = "InputObject" } }, { Name = "gameProcessedEvent", Type = { Category = "Primitive", Name = "bool" } } },
    From = "UserInputService"
}

class_members["UserInputService"]["TouchSwipe"] = {
    Type = "Event",
    Parameters = { { Name = "swipeDirection", Type = { Category = "Enum", Name = "SwipeDirection" } }, { Name = "numberOfTouches", Type = { Category = "Primitive", Name = "int" } }, { Name = "gameProcessedEvent", Type = { Category = "Primitive", Name = "bool" } } },
    From = "UserInputService"
}

class_members["UserInputService"]["TouchTap"] = {
    Type = "Event",
    Parameters = { { Name = "touchPositions", Type = { Category = "Group", Name = "Array" } }, { Name = "gameProcessedEvent", Type = { Category = "Primitive", Name = "bool" } } },
    From = "UserInputService"
}

class_members["UserInputService"]["TouchTapInWorld"] = {
    Type = "Event",
    Parameters = { { Name = "position", Type = { Category = "DataType", Name = "Vector2" } }, { Name = "processedByUI", Type = { Category = "Primitive", Name = "bool" } } },
    From = "UserInputService"
}

class_members["UserInputService"]["UserCFrameChanged"] = {
    Type = "Event",
    Parameters = { { Name = "type", Type = { Category = "Enum", Name = "UserCFrame" } }, { Name = "value", Type = { Category = "DataType", Name = "CFrame" } } },
    From = "UserInputService"
}

class_members["UserInputService"]["WindowFocusReleased"] = {
    Type = "Event",
    Parameters = {},
    From = "UserInputService"
}

class_members["UserInputService"]["WindowFocused"] = {
    Type = "Event",
    Parameters = {},
    From = "UserInputService"
}

class_members["UserInputService"]["childAdded"] = {
    Type = "Event",
    Parameters = { { Name = "child", Type = { Category = "Class", Name = "Instance" } } },
    From = "Instance"
}

return class_members
